/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ConsultationService } from "../consultation.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ConsultationCreateInput } from "./ConsultationCreateInput";
import { Consultation } from "./Consultation";
import { ConsultationFindManyArgs } from "./ConsultationFindManyArgs";
import { ConsultationWhereUniqueInput } from "./ConsultationWhereUniqueInput";
import { ConsultationUpdateInput } from "./ConsultationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ConsultationControllerBase {
  constructor(
    protected readonly service: ConsultationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Consultation })
  @nestAccessControl.UseRoles({
    resource: "Consultation",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createConsultation(
    @common.Body() data: ConsultationCreateInput
  ): Promise<Consultation> {
    return await this.service.createConsultation({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        dateTimeField: true,
        consultationStatusField: true,
        notesField: true,
        patientRefField: true,
        doctorRefField: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Consultation] })
  @ApiNestedQuery(ConsultationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Consultation",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async consultations(@common.Req() request: Request): Promise<Consultation[]> {
    const args = plainToClass(ConsultationFindManyArgs, request.query);
    return this.service.consultations({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        dateTimeField: true,
        consultationStatusField: true,
        notesField: true,
        patientRefField: true,
        doctorRefField: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Consultation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Consultation",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async consultation(
    @common.Param() params: ConsultationWhereUniqueInput
  ): Promise<Consultation | null> {
    const result = await this.service.consultation({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        dateTimeField: true,
        consultationStatusField: true,
        notesField: true,
        patientRefField: true,
        doctorRefField: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Consultation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Consultation",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateConsultation(
    @common.Param() params: ConsultationWhereUniqueInput,
    @common.Body() data: ConsultationUpdateInput
  ): Promise<Consultation | null> {
    try {
      return await this.service.updateConsultation({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          dateTimeField: true,
          consultationStatusField: true,
          notesField: true,
          patientRefField: true,
          doctorRefField: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Consultation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Consultation",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteConsultation(
    @common.Param() params: ConsultationWhereUniqueInput
  ): Promise<Consultation | null> {
    try {
      return await this.service.deleteConsultation({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          dateTimeField: true,
          consultationStatusField: true,
          notesField: true,
          patientRefField: true,
          doctorRefField: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
